name: ${name}
main: art.arcane.adapt.Adapt
version: ${version}
authors:
  - NextdoorPsycho
  - Cyberpwn
  - Vatuu
api-version: '${apiVersion}'
folia-supported: true
softdepend:
  - PlaceholderAPI
  - WorldGuard
  - Factions
  - ChestProtect
  - Residence
  - HiddenOre

commands:
  adapt: { }

permissions:
  adapt.idontknowwhatimdoingiswear:
    description: This is for the Adapt Testing command DEVELOPERS ONLY
    default: op
  adapt.listboosts:
    description: Allows for you to view the boosts on a player
    default: op
  adapt.opengui:
    description: Open the GUI without needing a Bookshelf
    default: op
  adapt.cheatitem:
    description: Allows for you to create a Cheat Item (one time use Xp Items)
    default: op
  adapt.boost:
    description: Allows for you to use the Boost command to boost XP gains
    default: op
  adapt.main:
    description: Allows for you to use the main command
    default: op
  adapt.configurator:
    description: Allows opening and using the in-game Adapt config editor
    default: op
  adapt.config:
    description: Legacy alias for adapt.configurator
    default: false
    children:
      adapt.configurator: true
  adapt.clear:
    description: Allows clearing player progression data
    default: op
  adapt.use.agility:
    description: Allow use of the skill Agility
    default: true
    children:
      adapt.use.agilityarmorup:
        description: Allow use of the adaptation AgilityArmorUp
        default: true
      adapt.use.agilitysuperjump:
        description: Allow use of the adaptation AgilitySuperJump
        default: true
      adapt.use.agilitywalljump:
        description: Allow use of the adaptation AgilityWallJump
        default: true
      adapt.use.agilitywindup:
        description: Allow use of the adaptation AgilityWindUp
        default: true
  adapt.use.architect:
    description: Allow use of the skill Architect
    default: true
    children:
      adapt.use.architectfoundation:
        description: Allow use of the adaptation ArchitectFoundation
        default: true
      adapt.use.architectglass:
        description: Allow use of the adaptation ArchitectGlass
        default: true
      adapt.use.architectplacement:
        description: Allow use of the adaptation ArchitectPlacement
        default: true
      adapt.use.architectwirelessredstone:
        description: Allow use of the adaptation ArchitectWirelessRedstone
        default: true
  adapt.use.axes:
    description: Allow use of the skill Axes
    default: true
    children:
      adapt.use.axechop:
        description: Allow use of the adaptation AxesChop
        default: true
      adapt.use.axedroptoinventory:
        description: Allow use of the adaptation AxesDropToInventory
        default: true
      adapt.use.axegroundsmash:
        description: Allow use of the adaptation AxesGroundSmash
        default: true
      adapt.use.axeleafveinminer:
        description: Allow use of the adaptation AxesLeafVeinMiner
        default: true
      adapt.use.axelogswap:
        description: Allow use of the adaptation AxesLogSwap
        default: true
      adapt.use.axewoodveinminer:
        description: Allow use of the adaptation AxesWoodVeinMiner
        default: true
  adapt.use.blocking:
    description: Allow use of the skill Blocking
    default: true
    children:
      adapt.use.blockingchainarmorer:
        description: Allow use of the adaptation BlockingChainArmorer
        default: true
      adapt.use.blockinghorsearmorer:
        description: Allow use of the adaptation BlockingHorseArmorer
        default: true
      adapt.use.blockingmultiarmor:
        description: Allow use of the adaptation BlockingMultiArmor
        default: true
      adapt.use.blockingsaddlecrafter:
        description: Allow use of the adaptation BlockingSaddleCrafter
        default: true
  adapt.use.brewing:
    description: Allow use of the skill Brewing
    default: true
    children:
      adapt.use.brewingabsorption:
        description: Allow use of the adaptation BrewingAbsorption
        default: true
      adapt.use.brewingblindness:
        description: Allow use of the adaptation BrewingBlindness
        default: true
      adapt.use.brewingdarkness:
        description: Allow use of the adaptation BrewingDarkness
        default: true
      adapt.use.brewingdecay:
        description: Allow use of the adaptation BrewingDecay
        default: true
      adapt.use.brewingfatigue:
        description: Allow use of the adaptation BrewingFatigue
        default: true
      adapt.use.brewinghaste:
        description: Allow use of the adaptation BrewingHaste
        default: true
      adapt.use.brewinghealthboost:
        description: Allow use of the adaptation BrewingHealthBoost
        default: true
      adapt.use.brewinghunger:
        description: Allow use of the adaptation BrewingHunger
        default: true
      adapt.use.brewinglingering:
        description: Allow use of the adaptation BrewingLingering
        default: true
      adapt.use.brewingnausea:
        description: Allow use of the adaptation BrewingNausea
        default: true
      adapt.use.brewingresistance:
        description: Allow use of the adaptation BrewingResistance
        default: true
      adapt.use.brewingsaturation:
        description: Allow use of the adaptation BrewingSaturation
        default: true
      adapt.use.brewingsuperheated:
        description: Allow use of the adaptation BrewingSuperheated
        default: true
  adapt.use.crafting:
    description: Allow use of the skill Crafting
    default: true
    children:
      adapt.use.craftingbackpacks:
        description: Allow use of the adaptation CraftingBackpacks
        default: true
      adapt.use.craftingdeconstruction:
        description: Allow use of the adaptation CraftingDeconstruction
        default: true
      adapt.use.craftingleather:
        description: Allow use of the adaptation CraftingLeather
        default: true
      adapt.use.craftingreconstruction:
        description: Allow use of the adaptation CraftingReconstruction
        default: true
      adapt.use.craftingskulls:
        description: Allow use of the adaptation CraftingSkulls
        default: true
      adapt.use.craftingstations:
        description: Allow use of the adaptation CraftingStations
        default: true
      adapt.use.craftingxp:
        description: Allow use of the adaptation CraftingXP
        default: true
  adapt.use.chronos:
    description: Allow use of the skill Chronos
    default: true
    children:
      adapt.use.chronostimebottle:
        description: Allow use of the adaptation ChronosTimeInABottle
        default: true
      adapt.use.chronosaberranttouch:
        description: Allow use of the adaptation ChronosAberrantTouch
        default: true
      adapt.use.chronosinstantrecall:
        description: Allow use of the adaptation ChronosInstantRecall
        default: true
      adapt.use.chronostimebomb:
        description: Allow use of the adaptation ChronosTimeBomb
        default: true
  adapt.use.discovery:
    description: Allow use of the skill Discovery
    default: true
    children:
      adapt.use.discoveryunity:
        description: Allow use of the adaptation DiscoveryUnity
        default: true
      adapt.use.discoveryvillageratt:
        description: Allow use of the adaptation DiscoveryVillagerAtt
        default: true
      adapt.use.discoveryworldarmor:
        description: Allow use of the adaptation DiscoveryWorldArmor
        default: true
      adapt.use.discoveryxpresist:
        description: Allow use of the adaptation DiscoveryXpResist
        default: true
  adapt.use.enchanting:
    description: Allow use of the skill Enchanting
    default: true
    children:
      adapt.use.enchantinglapisreturn:
        description: Allow use of the adaptation EnchantingLapisReturn
        default: true
      adapt.use.enchantingquickenchant:
        description: Allow use of the adaptation EnchantingQuickEnchant
        default: true
      adapt.use.enchantingxpreturn:
        description: Allow use of the adaptation EnchantingXpReturn
        default: true
  adapt.use.excavation:
    description: Allow use of the skill Excavation
    default: true
    children:
      adapt.use.excavationdroptoinventory:
        description: Allow use of the adaptation ExcavationDropToInventory
        default: true
      adapt.use.excavationhaste:
        description: Allow use of the adaptation ExcavationHaste
        default: true
      adapt.use.excavationomnitool:
        description: Allow use of the adaptation ExcavationOmnitool
        default: true
      adapt.use.excavationspelunker:
        description: Allow use of the adaptation ExcavationSpelunker
        default: true
  adapt.use.herbalism:
    description: Allow use of the skill Herbalism
    default: true
    children:
      adapt.use.herbalismcobweb:
        description: Allow use of the adaptation HerbalismCobweb
        default: true
      adapt.use.herbalismdroptoinventory:
        description: Allow use of the adaptation HerbalismDropToInventory
        default: true
      adapt.use.herbalismgrowthaura:
        description: Allow use of the adaptation HerbalismGrowthAura
        default: true
      adapt.use.herbalismhippo:
        description: Allow use of the adaptation HerbalismHippo
        default: true
      adapt.use.herbalismluck:
        description: Allow use of the adaptation HerbalismLuck
        default: true
      adapt.use.herbalismmyconid:
        description: Allow use of the adaptation HerbalismMyconid
        default: true
      adapt.use.herbalismreplant:
        description: Allow use of the adaptation HerbalismReplant
        default: true
      adapt.use.herbalismterralid:
        description: Allow use of the adaptation HerbalismTerralid
        default: true
      adapt.use.herbalismhungryshield:
        description: Allow use of the adaptation HerbalismHungryShield
        default: true
  adapt.use.hunter:
    description: Allow use of the skill Hunter
    default: true
    children:
      adapt.use.hunteradrenaline:
        description: Allow use of the adaptation HunterAdrenaline
        default: true
      adapt.use.hunterdroptoinventory:
        description: Allow use of the adaptation HunterDropToInventory
        default: true
      adapt.use.hunterinvis:
        description: Allow use of the adaptation HunterInvis
        default: true
      adapt.use.hunterjumpboost:
        description: Allow use of the adaptation HunterJumpBoost
        default: true
      adapt.use.hunterluck:
        description: Allow use of the adaptation HunterLuck
        default: true
      adapt.use.hunterspeed:
        description: Allow use of the adaptation HunterSpeed
        default: true
      adapt.use.hunterstrength:
        description: Allow use of the adaptation HunterStrength
        default: true
      adapt.use.hunterregen:
        description: Allow use of the adaptation HunterRegen
        default: true
      adapt.use.hunterresistance:
        description: Allow use of the adaptation HunterResistance
        default: true
  adapt.use.nether:
    description: Allow use of the skill Nether
    default: true
    children:
      adapt.use.netherskulltoss:
        description: Allow use of the adaptation NetherSkullToss
        default: true
      adapt.use.netherwitherresist:
        description: Allow use of the adaptation NetherWitherResist
        default: true
      adapt.use.netherfireresist:
        description: Allow use of the adaptation NetherFireResist
        default: true
  adapt.use.pickaxe:
    description: Allow use of the skill Pickaxe
    default: true
    children:
      adapt.use.pickaxeautosmelt:
        description: Allow use of the adaptation PickaxeAutoSmelt
        default: true
      adapt.use.pickaxedroptoinventory:
        description: Allow use of the adaptation PickaxeDropToInventory
        default: true
      adapt.use.pickaxechisel:
        description: Allow use of the adaptation PickaxeChisel
        default: true
      adapt.use.pickaxeveinminer:
        description: Allow use of the adaptation PickaxeVeinMiner
        default: true
  adapt.use.ranged:
    description: Allow use of the skill Ranged
    default: true
    children:
      adapt.use.rangedforce:
        description: Allow use of the adaptation RangedForce
        default: true
      adapt.use.rangedlungeshot:
        description: Allow use of the adaptation RangedLungeShot
        default: true
      adapt.use.rangedpiercing:
        description: Allow use of the adaptation RangedPiercing
        default: true
      adapt.use.rangedrecovery:
        description: Allow use of the adaptation RangedRecovery
        default: true
      adapt.use.rangedwebshot:
        description: Allow use of the adaptation RangedWebShot
        default: true
  adapt.use.rift:
    description: Allow use of the skill Rift
    default: true
    children:
      adapt.use.riftaccess:
        description: Allow use of the adaptation RiftAccess
        default: true
      adapt.use.riftblink:
        description: Allow use of the adaptation RiftBlink
        default: true
      adapt.use.riftdescent:
        description: Allow use of the adaptation RiftDescent
        default: true
      adapt.use.riftenderchest:
        description: Allow use of the adaptation RiftEnderChest
        default: true
      adapt.use.riftgate:
        description: Allow use of the adaptation RiftGate
        default: true
      adapt.use.riftresist:
        description: Allow use of the adaptation RiftResist
        default: true
      adapt.use.riftvisage:
        description: Allow use of the adaptation RiftVisage
        default: true
  adapt.use.seaborne:
    description: Allow use of the skill Seaborne
    default: true
    children:
      adapt.use.seabornefishersfantasy:
        description: Allow use of the adaptation SeaborneFishersFantasy
        default: true
      adapt.use.seabornespeed:
        description: Allow use of the adaptation SeaborneSpeed
        default: true
      adapt.use.seaborneoxygen:
        description: Allow use of the adaptation SeaborneOxygen
        default: true
      adapt.use.seaborneturtlesminingspeed:
        description: Allow use of the adaptation SeaborneTurtlesMiningSpeed
        default: true
      adapt.use.seaborneturtlesvision:
        description: Allow use of the adaptation SeaborneTurtlesVision
        default: true
  adapt.use.swords:
    description: Allow use of the skill Swords
    default: true
    children:
      adapt.use.swordbloodyblade:
        description: Allow use of the adaptation SwordBloodyBlade
        default: true
      adapt.use.swordmachete:
        description: Allow use of the adaptation SwordMachete
        default: true
      adapt.use.swordpoisonblade:
        description: Allow use of the adaptation SwordPoisonBlade
        default: true
  adapt.use.taming:
    description: Allow use of the skill Taming
    default: true
    children:
      adapt.use.tamehealth:
        description: Allow use of the adaptation TameHealth
        default: true
      adapt.use.tamedamage:
        description: Allow use of the adaptation TameDamage
        default: true
      adapt.use.tamehealthregeneration:
        description: Allow use of the adaptation TameHealthRegeneration
        default: true
  adapt.use.tragoul:
    description: Allow use of the skill Tragoul
    default: true
    children:
      adapt.use.tragoulglobe:
        description: Allow use of the adaptation TragoulGlobe
        default: true
      adapt.use.tragoulhealing:
        description: Allow use of the adaptation TragoulHealing
        default: true
      adapt.use.tragoullance:
        description: Allow use of the adaptation TragoulLance
        default: true
      adapt.use.tragoulthorns:
        description: Allow use of the adaptation TragoulThorns
        default: true
  adapt.use.unarmed:
    description: Allow use of the skill Unarmed
    default: true
    children:
      adapt.use.unarmedglasscannon:
        description: Allow use of the adaptation UnarmedGlassCannon
        default: true
      adapt.use.unarmedpower:
        description: Allow use of the adaptation UnarmedPower
        default: true
      adapt.use.unarmedsuckerpunch:
        description: Allow use of the adaptation UnarmedSuckerPunch
        default: true
