name: Adapt Feature Request
description: File a feature request for Adapt, the features are NOT intended to replace other plugins (though, i would not mind doing it) all features should feel effortless on the player to be using.
labels: [ feature ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill this out!
        If this does not work for you, feel free to use the [blank](https://github.com/VolmitSoftware/Adapt/issues/new) format.
  - type: dropdown
    id: arc
    attributes:
      label: Adding, Removing, or Changing
      description: What are you doing
      options:
        - Adding
        - Removing
        - Changing
    validations:
      required: true
  - type: input
    id: atype
    attributes:
      label: Type of Modification
      description: What is it for?
      value: I want to ...
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: What are you trying to modify
      description: Give as detailed of a description as you can for the skill that you want (include pictures/Videos if applicable)
      value: The way I would implement this is ...
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Alternatives
      description: What alternatives have you considered?
      value: plugins... commands...
  - type: markdown
    attributes:
      value: "Thank you for filling out the form! We read it soon.."
