/*------------------------------------------------------------------------------
 -   Adapt is a Skill/Integration plugin  for Minecraft Bukkit Servers
 -   Copyright (c) 2022 Arcane Arts (Volmit Software)
 -
 -   This program is free software: you can redistribute it and/or modify
 -   it under the terms of the GNU General Public License as published by
 -   the Free Software Foundation, either version 3 of the License, or
 -   (at your option) any later version.
 -
 -   This program is distributed in the hope that it will be useful,
 -   but WITHOUT ANY WARRANTY; without even the implied warranty of
 -   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 -   GNU General Public License for more details.
 -
 -   You should have received a copy of the GNU General Public License
 -   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 -----------------------------------------------------------------------------*/

package art.arcane.adapt.content.adaptation.axe;

import art.arcane.adapt.api.adaptation.AdaptationConfig;
import art.arcane.adapt.api.adaptation.SimpleAdaptation;
import art.arcane.adapt.api.advancement.AdaptAdvancement;
import art.arcane.adapt.api.advancement.AdaptAdvancementFrame;
import art.arcane.adapt.api.advancement.AdvancementVisibility;
import art.arcane.adapt.api.fx.FxPriority;
import art.arcane.adapt.api.recipe.AdaptRecipe;
import art.arcane.adapt.util.common.format.C;
import art.arcane.adapt.util.common.format.Localizer;
import art.arcane.adapt.util.config.ConfigDescription;
import art.arcane.adapt.util.reflect.registries.Materials;
import art.arcane.adapt.util.reflect.registries.Particles;
import art.arcane.volmlib.util.inventorygui.Element;
import org.bukkit.Material;
import org.bukkit.Sound;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.inventory.CraftItemEvent;
import org.bukkit.inventory.ItemStack;

public class AxeCraftLogSwap extends SimpleAdaptation<AxeCraftLogSwap.Config> {

  public AxeCraftLogSwap() {
    super("axe-logswap");
    registerConfiguration(Config.class);
    setLocalizationKey("axe.log_swap");
    setIcon(Material.MUDDY_MANGROVE_ROOTS);
    setInterval(17773);

    //Birch -> Types
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapbirchoak")
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.OAK_SAPLING)
        .result(new ItemStack(Material.OAK_PLANKS, 1))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapbirchacacia")
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.ACACIA_SAPLING)
        .result(new ItemStack(Material.ACACIA_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapbirchdarkoak")
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.DARK_OAK_SAPLING)
        .result(new ItemStack(Material.DARK_OAK_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapbirchjungle")
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.JUNGLE_SAPLING)
        .result(new ItemStack(Material.JUNGLE_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapbirchspruce")
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.SPRUCE_SAPLING)
        .result(new ItemStack(Material.SPRUCE_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapbirchmangrove")
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.BIRCH_LOG)
        .ingredient(Material.MANGROVE_PROPAGULE)
        .result(new ItemStack(Material.MANGROVE_LOG, 8))
        .build());
    if (Materials.CHERRY_LOG != null && Materials.CHERRY_SAPLING != null) {
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swapbirchcherry")
          .ingredient(Material.BIRCH_LOG)
          .ingredient(Material.BIRCH_LOG)
          .ingredient(Material.BIRCH_LOG)
          .ingredient(Material.BIRCH_LOG)
          .ingredient(Material.BIRCH_LOG)
          .ingredient(Material.BIRCH_LOG)
          .ingredient(Material.BIRCH_LOG)
          .ingredient(Material.BIRCH_LOG)
          .ingredient(Materials.CHERRY_SAPLING)
          .result(new ItemStack(Materials.CHERRY_LOG, 8))
          .build());
    }
    if (Materials.PALE_OAK_LOG != null && Materials.PALE_OAK_SAPLING != null) {
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swapbirchpaleoak")
          .ingredient(Material.BIRCH_LOG)
          .ingredient(Material.BIRCH_LOG)
          .ingredient(Material.BIRCH_LOG)
          .ingredient(Material.BIRCH_LOG)
          .ingredient(Material.BIRCH_LOG)
          .ingredient(Material.BIRCH_LOG)
          .ingredient(Material.BIRCH_LOG)
          .ingredient(Material.BIRCH_LOG)
          .ingredient(Materials.PALE_OAK_SAPLING)
          .result(new ItemStack(Materials.PALE_OAK_LOG, 8))
          .build());
    }

    //Oak -> Types
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapoakbirch")
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.BIRCH_SAPLING)
        .result(new ItemStack(Material.BIRCH_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapoakacacia")
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.ACACIA_SAPLING)
        .result(new ItemStack(Material.ACACIA_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapoakdarkoak")
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.DARK_OAK_SAPLING)
        .result(new ItemStack(Material.DARK_OAK_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapoakjungle")
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.JUNGLE_SAPLING)
        .result(new ItemStack(Material.JUNGLE_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapoakspruce")
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.SPRUCE_SAPLING)
        .result(new ItemStack(Material.SPRUCE_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapoakmangrove")
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.OAK_LOG)
        .ingredient(Material.MANGROVE_PROPAGULE)
        .result(new ItemStack(Material.MANGROVE_LOG, 8))
        .build());
    if (Materials.CHERRY_LOG != null && Materials.CHERRY_SAPLING != null) {
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swapoakcherry")
          .ingredient(Material.OAK_LOG)
          .ingredient(Material.OAK_LOG)
          .ingredient(Material.OAK_LOG)
          .ingredient(Material.OAK_LOG)
          .ingredient(Material.OAK_LOG)
          .ingredient(Material.OAK_LOG)
          .ingredient(Material.OAK_LOG)
          .ingredient(Material.OAK_LOG)
          .ingredient(Materials.CHERRY_SAPLING)
          .result(new ItemStack(Materials.CHERRY_LOG, 8))
          .build());
    }
    if (Materials.PALE_OAK_LOG != null && Materials.PALE_OAK_SAPLING != null) {
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swapoakpaleoak")
          .ingredient(Material.OAK_LOG)
          .ingredient(Material.OAK_LOG)
          .ingredient(Material.OAK_LOG)
          .ingredient(Material.OAK_LOG)
          .ingredient(Material.OAK_LOG)
          .ingredient(Material.OAK_LOG)
          .ingredient(Material.OAK_LOG)
          .ingredient(Material.OAK_LOG)
          .ingredient(Materials.PALE_OAK_SAPLING)
          .result(new ItemStack(Materials.PALE_OAK_LOG, 8))
          .build());
    }

    //Acacia -> Types
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapacaciabirch")
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.BIRCH_SAPLING)
        .result(new ItemStack(Material.BIRCH_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapacaciaoak")
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.OAK_SAPLING)
        .result(new ItemStack(Material.OAK_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapacaciadarkoak")
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.DARK_OAK_SAPLING)
        .result(new ItemStack(Material.DARK_OAK_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapacaciajungle")
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.JUNGLE_SAPLING)
        .result(new ItemStack(Material.JUNGLE_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapacaciaspruce")
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.SPRUCE_SAPLING)
        .result(new ItemStack(Material.SPRUCE_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapacaciamangrove")
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.ACACIA_LOG)
        .ingredient(Material.MANGROVE_PROPAGULE)
        .result(new ItemStack(Material.MANGROVE_LOG, 8))
        .build());
    if (Materials.CHERRY_LOG != null && Materials.CHERRY_SAPLING != null) {
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swapacaciacherry")
          .ingredient(Material.ACACIA_LOG)
          .ingredient(Material.ACACIA_LOG)
          .ingredient(Material.ACACIA_LOG)
          .ingredient(Material.ACACIA_LOG)
          .ingredient(Material.ACACIA_LOG)
          .ingredient(Material.ACACIA_LOG)
          .ingredient(Material.ACACIA_LOG)
          .ingredient(Material.ACACIA_LOG)
          .ingredient(Materials.CHERRY_SAPLING)
          .result(new ItemStack(Materials.CHERRY_LOG, 8))
          .build());
    }
    if (Materials.PALE_OAK_LOG != null && Materials.PALE_OAK_SAPLING != null) {
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swapacaciapaleoak")
          .ingredient(Material.ACACIA_LOG)
          .ingredient(Material.ACACIA_LOG)
          .ingredient(Material.ACACIA_LOG)
          .ingredient(Material.ACACIA_LOG)
          .ingredient(Material.ACACIA_LOG)
          .ingredient(Material.ACACIA_LOG)
          .ingredient(Material.ACACIA_LOG)
          .ingredient(Material.ACACIA_LOG)
          .ingredient(Materials.PALE_OAK_SAPLING)
          .result(new ItemStack(Materials.PALE_OAK_LOG, 8))
          .build());
    }

    //Dark Oak -> Types
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapdarkoakbirch")
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.BIRCH_SAPLING)
        .result(new ItemStack(Material.BIRCH_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapdarkoakoak")
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.OAK_SAPLING)
        .result(new ItemStack(Material.OAK_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapdarkoakacacia")
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.ACACIA_SAPLING)
        .result(new ItemStack(Material.ACACIA_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapdarkoakjungle")
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.JUNGLE_SAPLING)
        .result(new ItemStack(Material.JUNGLE_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapdarkoakspruce")
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.SPRUCE_SAPLING)
        .result(new ItemStack(Material.SPRUCE_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapdarkoakmangrove")
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.DARK_OAK_LOG)
        .ingredient(Material.MANGROVE_PROPAGULE)
        .result(new ItemStack(Material.MANGROVE_LOG, 8))
        .build());
    if (Materials.CHERRY_LOG != null && Materials.CHERRY_SAPLING != null) {
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swapdarkoakcherry")
          .ingredient(Material.DARK_OAK_LOG)
          .ingredient(Material.DARK_OAK_LOG)
          .ingredient(Material.DARK_OAK_LOG)
          .ingredient(Material.DARK_OAK_LOG)
          .ingredient(Material.DARK_OAK_LOG)
          .ingredient(Material.DARK_OAK_LOG)
          .ingredient(Material.DARK_OAK_LOG)
          .ingredient(Material.DARK_OAK_LOG)
          .ingredient(Materials.CHERRY_SAPLING)
          .result(new ItemStack(Materials.CHERRY_LOG, 8))
          .build());
    }
    if (Materials.PALE_OAK_LOG != null && Materials.PALE_OAK_SAPLING != null) {
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swapdarkoakpaleoak")
          .ingredient(Material.DARK_OAK_LOG)
          .ingredient(Material.DARK_OAK_LOG)
          .ingredient(Material.DARK_OAK_LOG)
          .ingredient(Material.DARK_OAK_LOG)
          .ingredient(Material.DARK_OAK_LOG)
          .ingredient(Material.DARK_OAK_LOG)
          .ingredient(Material.DARK_OAK_LOG)
          .ingredient(Material.DARK_OAK_LOG)
          .ingredient(Materials.PALE_OAK_SAPLING)
          .result(new ItemStack(Materials.PALE_OAK_LOG, 8))
          .build());
    }

    //Jungle -> Types
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapjunglebirch")
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.BIRCH_SAPLING)
        .result(new ItemStack(Material.BIRCH_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapjungleoak")
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.OAK_SAPLING)
        .result(new ItemStack(Material.OAK_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapjungleacacia")
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.ACACIA_SAPLING)
        .result(new ItemStack(Material.ACACIA_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapjungledarkoak")
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.DARK_OAK_SAPLING)
        .result(new ItemStack(Material.DARK_OAK_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapjunglespruce")
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.SPRUCE_SAPLING)
        .result(new ItemStack(Material.SPRUCE_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapjunglemangrove")
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.JUNGLE_LOG)
        .ingredient(Material.MANGROVE_PROPAGULE)
        .result(new ItemStack(Material.MANGROVE_LOG, 8))
        .build());
    if (Materials.CHERRY_LOG != null && Materials.CHERRY_SAPLING != null) {
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swapjunglecherry")
          .ingredient(Material.JUNGLE_LOG)
          .ingredient(Material.JUNGLE_LOG)
          .ingredient(Material.JUNGLE_LOG)
          .ingredient(Material.JUNGLE_LOG)
          .ingredient(Material.JUNGLE_LOG)
          .ingredient(Material.JUNGLE_LOG)
          .ingredient(Material.JUNGLE_LOG)
          .ingredient(Material.JUNGLE_LOG)
          .ingredient(Materials.CHERRY_SAPLING)
          .result(new ItemStack(Materials.CHERRY_LOG, 8))
          .build());
    }
    if (Materials.PALE_OAK_LOG != null && Materials.PALE_OAK_SAPLING != null) {
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swapjunglepaleoak")
          .ingredient(Material.JUNGLE_LOG)
          .ingredient(Material.JUNGLE_LOG)
          .ingredient(Material.JUNGLE_LOG)
          .ingredient(Material.JUNGLE_LOG)
          .ingredient(Material.JUNGLE_LOG)
          .ingredient(Material.JUNGLE_LOG)
          .ingredient(Material.JUNGLE_LOG)
          .ingredient(Material.JUNGLE_LOG)
          .ingredient(Materials.PALE_OAK_SAPLING)
          .result(new ItemStack(Materials.PALE_OAK_LOG, 8))
          .build());
    }

    //Spruce -> Types
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapsprucebirch")
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.BIRCH_SAPLING)
        .result(new ItemStack(Material.BIRCH_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapspruceoak")
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.OAK_SAPLING)
        .result(new ItemStack(Material.OAK_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapspruceacacia")
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.ACACIA_SAPLING)
        .result(new ItemStack(Material.ACACIA_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapsprucedarkoak")
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.DARK_OAK_SAPLING)
        .result(new ItemStack(Material.DARK_OAK_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapsprucejungle")
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.JUNGLE_SAPLING)
        .result(new ItemStack(Material.JUNGLE_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapsprucemangrove")
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.SPRUCE_LOG)
        .ingredient(Material.MANGROVE_PROPAGULE)
        .result(new ItemStack(Material.MANGROVE_LOG, 8))
        .build());
    if (Materials.CHERRY_LOG != null && Materials.CHERRY_SAPLING != null) {
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swapsprucecherry")
          .ingredient(Material.SPRUCE_LOG)
          .ingredient(Material.SPRUCE_LOG)
          .ingredient(Material.SPRUCE_LOG)
          .ingredient(Material.SPRUCE_LOG)
          .ingredient(Material.SPRUCE_LOG)
          .ingredient(Material.SPRUCE_LOG)
          .ingredient(Material.SPRUCE_LOG)
          .ingredient(Material.SPRUCE_LOG)
          .ingredient(Materials.CHERRY_SAPLING)
          .result(new ItemStack(Materials.CHERRY_LOG, 8))
          .build());
    }
    if (Materials.PALE_OAK_LOG != null && Materials.PALE_OAK_SAPLING != null) {
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swapsprucepaleoak")
          .ingredient(Material.SPRUCE_LOG)
          .ingredient(Material.SPRUCE_LOG)
          .ingredient(Material.SPRUCE_LOG)
          .ingredient(Material.SPRUCE_LOG)
          .ingredient(Material.SPRUCE_LOG)
          .ingredient(Material.SPRUCE_LOG)
          .ingredient(Material.SPRUCE_LOG)
          .ingredient(Material.SPRUCE_LOG)
          .ingredient(Materials.PALE_OAK_SAPLING)
          .result(new ItemStack(Materials.PALE_OAK_LOG, 8))
          .build());
    }

    //Mangrove -> Types
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapmangrovebirch")
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.BIRCH_SAPLING)
        .result(new ItemStack(Material.BIRCH_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapmangroveoak")
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.OAK_SAPLING)
        .result(new ItemStack(Material.OAK_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapmangroveacacia")
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.ACACIA_SAPLING)
        .result(new ItemStack(Material.ACACIA_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapmangrovedarkoak")
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.DARK_OAK_SAPLING)
        .result(new ItemStack(Material.DARK_OAK_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapmangrovejungle")
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.JUNGLE_SAPLING)
        .result(new ItemStack(Material.JUNGLE_LOG, 8))
        .build());
    registerRecipe(AdaptRecipe.shapeless()
        .key("axe-swapmangrovespruce")
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.MANGROVE_LOG)
        .ingredient(Material.SPRUCE_SAPLING)
        .result(new ItemStack(Material.SPRUCE_LOG, 8))
        .build());
    if (Materials.CHERRY_LOG != null && Materials.CHERRY_SAPLING != null) {
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swapmangrovecherry")
          .ingredient(Material.MANGROVE_LOG)
          .ingredient(Material.MANGROVE_LOG)
          .ingredient(Material.MANGROVE_LOG)
          .ingredient(Material.MANGROVE_LOG)
          .ingredient(Material.MANGROVE_LOG)
          .ingredient(Material.MANGROVE_LOG)
          .ingredient(Material.MANGROVE_LOG)
          .ingredient(Material.MANGROVE_LOG)
          .ingredient(Materials.CHERRY_SAPLING)
          .result(new ItemStack(Materials.CHERRY_LOG, 8))
          .build());
    }
    if (Materials.PALE_OAK_LOG != null && Materials.PALE_OAK_SAPLING != null) {
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swapmangrovepaleoak")
          .ingredient(Material.MANGROVE_LOG)
          .ingredient(Material.MANGROVE_LOG)
          .ingredient(Material.MANGROVE_LOG)
          .ingredient(Material.MANGROVE_LOG)
          .ingredient(Material.MANGROVE_LOG)
          .ingredient(Material.MANGROVE_LOG)
          .ingredient(Material.MANGROVE_LOG)
          .ingredient(Material.MANGROVE_LOG)
          .ingredient(Materials.PALE_OAK_SAPLING)
          .result(new ItemStack(Materials.PALE_OAK_LOG, 8))
          .build());
    }

    //Cherry -> Types
    if (Materials.CHERRY_LOG != null && Materials.CHERRY_SAPLING != null) {
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swapcherrybirch")
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Material.BIRCH_SAPLING)
          .result(new ItemStack(Material.BIRCH_LOG, 8))
          .build());
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swapcherryoak")
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Material.OAK_SAPLING)
          .result(new ItemStack(Material.OAK_LOG, 8))
          .build());
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swapcherryacacia")
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Material.ACACIA_SAPLING)
          .result(new ItemStack(Material.ACACIA_LOG, 8))
          .build());
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swapcherrydarkoak")
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Material.DARK_OAK_SAPLING)
          .result(new ItemStack(Material.DARK_OAK_LOG, 8))
          .build());
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swapcherryjungle")
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Material.JUNGLE_SAPLING)
          .result(new ItemStack(Material.JUNGLE_LOG, 8))
          .build());
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swapcherryspruce")
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Materials.CHERRY_LOG)
          .ingredient(Material.SPRUCE_SAPLING)
          .result(new ItemStack(Material.SPRUCE_LOG, 8))
          .build());
      if (Materials.PALE_OAK_LOG != null && Materials.PALE_OAK_SAPLING != null) {
        registerRecipe(AdaptRecipe.shapeless()
            .key("axe-swapcherrypaleoak")
            .ingredient(Materials.CHERRY_LOG)
            .ingredient(Materials.CHERRY_LOG)
            .ingredient(Materials.CHERRY_LOG)
            .ingredient(Materials.CHERRY_LOG)
            .ingredient(Materials.CHERRY_LOG)
            .ingredient(Materials.CHERRY_LOG)
            .ingredient(Materials.CHERRY_LOG)
            .ingredient(Materials.CHERRY_LOG)
            .ingredient(Materials.PALE_OAK_SAPLING)
            .result(new ItemStack(Materials.PALE_OAK_LOG, 8))
            .build());
      }
    }

    //Pale Oak -> Types
    if (Materials.PALE_OAK_LOG != null && Materials.PALE_OAK_SAPLING != null) {
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swappaleoakbirch")
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Material.BIRCH_SAPLING)
          .result(new ItemStack(Material.BIRCH_LOG, 8))
          .build());
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swappaleoakoak")
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Material.OAK_SAPLING)
          .result(new ItemStack(Material.OAK_LOG, 8))
          .build());
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swappaleoakacacia")
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Material.ACACIA_SAPLING)
          .result(new ItemStack(Material.ACACIA_LOG, 8))
          .build());
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swappaleoakdarkoak")
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Material.DARK_OAK_SAPLING)
          .result(new ItemStack(Material.DARK_OAK_LOG, 8))
          .build());
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swappaleoakjungle")
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Material.JUNGLE_SAPLING)
          .result(new ItemStack(Material.JUNGLE_LOG, 8))
          .build());
      registerRecipe(AdaptRecipe.shapeless()
          .key("axe-swappaleoakspruce")
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Materials.PALE_OAK_LOG)
          .ingredient(Material.SPRUCE_SAPLING)
          .result(new ItemStack(Material.SPRUCE_LOG, 8))
          .build());
      if (Materials.CHERRY_LOG != null && Materials.CHERRY_SAPLING != null) {
        registerRecipe(AdaptRecipe.shapeless()
            .key("axe-swappaleoakcherry")
            .ingredient(Materials.PALE_OAK_LOG)
            .ingredient(Materials.PALE_OAK_LOG)
            .ingredient(Materials.PALE_OAK_LOG)
            .ingredient(Materials.PALE_OAK_LOG)
            .ingredient(Materials.PALE_OAK_LOG)
            .ingredient(Materials.PALE_OAK_LOG)
            .ingredient(Materials.PALE_OAK_LOG)
            .ingredient(Materials.PALE_OAK_LOG)
            .ingredient(Materials.CHERRY_SAPLING)
            .result(new ItemStack(Materials.CHERRY_LOG, 8))
            .build());
      }
    }
    registerAdvancement(AdaptAdvancement.builder()
        .icon(Material.OAK_SAPLING)
        .key("challenge_axe_log_swap_500")
        .frame(AdaptAdvancementFrame.CHALLENGE)
        .visibility(AdvancementVisibility.PARENT_GRANTED)
        .build());
    registerMilestone("challenge_axe_log_swap_500", "axe.log-swap.conversions", 500, 400);
  }

  @Override
  public void addStats(int level, Element v) {
    v.addLore(C.GREEN + "+ " + C.GRAY + Localizer.dLocalize("axe.log_swap.lore1"));
  }

  @EventHandler(priority = EventPriority.MONITOR)
  public void on(CraftItemEvent e) {
    if (!(e.getWhoClicked() instanceof Player p) || !hasActiveAdaptation(p)) {
      return;
    }
    if (e.getRecipe() instanceof org.bukkit.inventory.ShapelessRecipe recipe && recipe.getKey().getNamespace().equals("adapt") && recipe.getKey().getKey().startsWith("axe-swap")) {
      addStat(p, "axe.log-swap.conversions", 1);
      fx(p.getLocation().add(0.0D, 1.0D, 0.0D), FxPriority.TRANSITION)
          .particle(Particles.VILLAGER_HAPPY, 8, 0.0D, 0.0D, 0.0D, 0.4D, 0.02D)
          .dustBurst(4, 0.3D, 1.0F)
          .chord(Sound.BLOCK_SWEET_BERRY_BUSH_PICK_BERRIES, 0.6F, 1.2F, Sound.BLOCK_AMETHYST_BLOCK_CHIME, 0.4F, 1.6F);
    }
  }

  @Override
  public void onTick() {
  }

  @ConfigDescription("Convert log types using a sapling in a crafting table.")
  protected static class Config extends AdaptationConfig {
    public Config() {
      permanent = true;
      baseCost = 2;
      costFactor = 1;
      maxLevel = 1;
    }
  }
}