/*------------------------------------------------------------------------------
 -   Adapt is a Skill/Integration plugin  for Minecraft Bukkit Servers
 -   Copyright (c) 2022 Arcane Arts (Volmit Software)
 -
 -   This program is free software: you can redistribute it and/or modify
 -   it under the terms of the GNU General Public License as published by
 -   the Free Software Foundation, either version 3 of the License, or
 -   (at your option) any later version.
 -
 -   This program is distributed in the hope that it will be useful,
 -   but WITHOUT ANY WARRANTY; without even the implied warranty of
 -   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 -   GNU General Public License for more details.
 -
 -   You should have received a copy of the GNU General Public License
 -   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 -----------------------------------------------------------------------------*/

package com.volmit.adapt.content.adaptation.axe;

import com.volmit.adapt.api.adaptation.SimpleAdaptation;
import com.volmit.adapt.api.recipe.AdaptRecipe;
import com.volmit.adapt.util.C;
import com.volmit.adapt.util.Element;
import com.volmit.adapt.util.Localizer;
import lombok.NoArgsConstructor;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;
import com.volmit.adapt.util.reflect.registries.Materials;

public class AxeCraftLogSwap extends SimpleAdaptation<AxeCraftLogSwap.Config> {

    public AxeCraftLogSwap() {
        super("axe-logswap");
        registerConfiguration(Config.class);
        setDescription(Localizer.dLocalize("axe.log_swap.description"));
        setDisplayName(Localizer.dLocalize("axe.log_swap.name"));
        setIcon(Material.MUDDY_MANGROVE_ROOTS);
        setBaseCost(getConfig().baseCost);
        setCostFactor(getConfig().costFactor);
        setMaxLevel(getConfig().maxLevel);
        setInitialCost(getConfig().initialCost);
        setInterval(17773);

        //Birch -> Types
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapbirchoak")
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.OAK_SAPLING)
                .result(new ItemStack(Material.OAK_PLANKS, 1))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapbirchacacia")
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.ACACIA_SAPLING)
                .result(new ItemStack(Material.ACACIA_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapbirchdarkoak")
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.DARK_OAK_SAPLING)
                .result(new ItemStack(Material.DARK_OAK_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapbirchjungle")
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.JUNGLE_SAPLING)
                .result(new ItemStack(Material.JUNGLE_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapbirchspruce")
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.SPRUCE_SAPLING)
                .result(new ItemStack(Material.SPRUCE_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapbirchmangrove")
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.BIRCH_LOG)
                .ingredient(Material.MANGROVE_PROPAGULE)
                .result(new ItemStack(Material.MANGROVE_LOG, 8))
                .build());
        if (Materials.CHERRY_LOG != null && Materials.CHERRY_SAPLING != null) {
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swapbirchcherry")
                    .ingredient(Material.BIRCH_LOG)
                    .ingredient(Material.BIRCH_LOG)
                    .ingredient(Material.BIRCH_LOG)
                    .ingredient(Material.BIRCH_LOG)
                    .ingredient(Material.BIRCH_LOG)
                    .ingredient(Material.BIRCH_LOG)
                    .ingredient(Material.BIRCH_LOG)
                    .ingredient(Material.BIRCH_LOG)
                    .ingredient(Materials.CHERRY_SAPLING)
                    .result(new ItemStack(Materials.CHERRY_LOG, 8))
                    .build());
        }
        if (Materials.PALE_OAK_LOG != null && Materials.PALE_OAK_SAPLING != null) {
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swapbirchpaleoak")
                    .ingredient(Material.BIRCH_LOG)
                    .ingredient(Material.BIRCH_LOG)
                    .ingredient(Material.BIRCH_LOG)
                    .ingredient(Material.BIRCH_LOG)
                    .ingredient(Material.BIRCH_LOG)
                    .ingredient(Material.BIRCH_LOG)
                    .ingredient(Material.BIRCH_LOG)
                    .ingredient(Material.BIRCH_LOG)
                    .ingredient(Materials.PALE_OAK_SAPLING)
                    .result(new ItemStack(Materials.PALE_OAK_LOG, 8))
                    .build());
        }

        //Oak -> Types
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapoakbirch")
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.BIRCH_SAPLING)
                .result(new ItemStack(Material.BIRCH_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapoakacacia")
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.ACACIA_SAPLING)
                .result(new ItemStack(Material.ACACIA_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapoakdarkoak")
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.DARK_OAK_SAPLING)
                .result(new ItemStack(Material.DARK_OAK_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapoakjungle")
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.JUNGLE_SAPLING)
                .result(new ItemStack(Material.JUNGLE_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapoakspruce")
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.SPRUCE_SAPLING)
                .result(new ItemStack(Material.SPRUCE_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapoakmangrove")
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.OAK_LOG)
                .ingredient(Material.MANGROVE_PROPAGULE)
                .result(new ItemStack(Material.MANGROVE_LOG, 8))
                .build());
        if (Materials.CHERRY_LOG != null && Materials.CHERRY_SAPLING != null) {
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swapoakcherry")
                    .ingredient(Material.OAK_LOG)
                    .ingredient(Material.OAK_LOG)
                    .ingredient(Material.OAK_LOG)
                    .ingredient(Material.OAK_LOG)
                    .ingredient(Material.OAK_LOG)
                    .ingredient(Material.OAK_LOG)
                    .ingredient(Material.OAK_LOG)
                    .ingredient(Material.OAK_LOG)
                    .ingredient(Materials.CHERRY_SAPLING)
                    .result(new ItemStack(Materials.CHERRY_LOG, 8))
                    .build());
        }
        if (Materials.PALE_OAK_LOG != null && Materials.PALE_OAK_SAPLING != null) {
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swapoakpaleoak")
                    .ingredient(Material.OAK_LOG)
                    .ingredient(Material.OAK_LOG)
                    .ingredient(Material.OAK_LOG)
                    .ingredient(Material.OAK_LOG)
                    .ingredient(Material.OAK_LOG)
                    .ingredient(Material.OAK_LOG)
                    .ingredient(Material.OAK_LOG)
                    .ingredient(Material.OAK_LOG)
                    .ingredient(Materials.PALE_OAK_SAPLING)
                    .result(new ItemStack(Materials.PALE_OAK_LOG, 8))
                    .build());
        }

        //Acacia -> Types
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapacaciabirch")
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.BIRCH_SAPLING)
                .result(new ItemStack(Material.BIRCH_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapacaciaoak")
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.OAK_SAPLING)
                .result(new ItemStack(Material.OAK_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapacaciadarkoak")
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.DARK_OAK_SAPLING)
                .result(new ItemStack(Material.DARK_OAK_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapacaciajungle")
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.JUNGLE_SAPLING)
                .result(new ItemStack(Material.JUNGLE_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapacaciaspruce")
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.SPRUCE_SAPLING)
                .result(new ItemStack(Material.SPRUCE_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapacaciamangrove")
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.ACACIA_LOG)
                .ingredient(Material.MANGROVE_PROPAGULE)
                .result(new ItemStack(Material.MANGROVE_LOG, 8))
                .build());
        if (Materials.CHERRY_LOG != null && Materials.CHERRY_SAPLING != null) {
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swapacaciacherry")
                    .ingredient(Material.ACACIA_LOG)
                    .ingredient(Material.ACACIA_LOG)
                    .ingredient(Material.ACACIA_LOG)
                    .ingredient(Material.ACACIA_LOG)
                    .ingredient(Material.ACACIA_LOG)
                    .ingredient(Material.ACACIA_LOG)
                    .ingredient(Material.ACACIA_LOG)
                    .ingredient(Material.ACACIA_LOG)
                    .ingredient(Materials.CHERRY_SAPLING)
                    .result(new ItemStack(Materials.CHERRY_LOG, 8))
                    .build());
        }
        if (Materials.PALE_OAK_LOG != null && Materials.PALE_OAK_SAPLING != null) {
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swapacaciapaleoak")
                    .ingredient(Material.ACACIA_LOG)
                    .ingredient(Material.ACACIA_LOG)
                    .ingredient(Material.ACACIA_LOG)
                    .ingredient(Material.ACACIA_LOG)
                    .ingredient(Material.ACACIA_LOG)
                    .ingredient(Material.ACACIA_LOG)
                    .ingredient(Material.ACACIA_LOG)
                    .ingredient(Material.ACACIA_LOG)
                    .ingredient(Materials.PALE_OAK_SAPLING)
                    .result(new ItemStack(Materials.PALE_OAK_LOG, 8))
                    .build());
        }

        //Dark Oak -> Types
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapdarkoakbirch")
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.BIRCH_SAPLING)
                .result(new ItemStack(Material.BIRCH_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapdarkoakoak")
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.OAK_SAPLING)
                .result(new ItemStack(Material.OAK_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapdarkoakacacia")
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.ACACIA_SAPLING)
                .result(new ItemStack(Material.ACACIA_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapdarkoakjungle")
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.JUNGLE_SAPLING)
                .result(new ItemStack(Material.JUNGLE_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapdarkoakspruce")
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.SPRUCE_SAPLING)
                .result(new ItemStack(Material.SPRUCE_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapdarkoakmangrove")
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.DARK_OAK_LOG)
                .ingredient(Material.MANGROVE_PROPAGULE)
                .result(new ItemStack(Material.MANGROVE_LOG, 8))
                .build());
        if (Materials.CHERRY_LOG != null && Materials.CHERRY_SAPLING != null) {
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swapdarkoakcherry")
                    .ingredient(Material.DARK_OAK_LOG)
                    .ingredient(Material.DARK_OAK_LOG)
                    .ingredient(Material.DARK_OAK_LOG)
                    .ingredient(Material.DARK_OAK_LOG)
                    .ingredient(Material.DARK_OAK_LOG)
                    .ingredient(Material.DARK_OAK_LOG)
                    .ingredient(Material.DARK_OAK_LOG)
                    .ingredient(Material.DARK_OAK_LOG)
                    .ingredient(Materials.CHERRY_SAPLING)
                    .result(new ItemStack(Materials.CHERRY_LOG, 8))
                    .build());
        }
        if (Materials.PALE_OAK_LOG != null && Materials.PALE_OAK_SAPLING != null) {
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swapdarkoakpaleoak")
                    .ingredient(Material.DARK_OAK_LOG)
                    .ingredient(Material.DARK_OAK_LOG)
                    .ingredient(Material.DARK_OAK_LOG)
                    .ingredient(Material.DARK_OAK_LOG)
                    .ingredient(Material.DARK_OAK_LOG)
                    .ingredient(Material.DARK_OAK_LOG)
                    .ingredient(Material.DARK_OAK_LOG)
                    .ingredient(Material.DARK_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_SAPLING)
                    .result(new ItemStack(Materials.PALE_OAK_LOG, 8))
                    .build());
        }

        //Jungle -> Types
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapjunglebirch")
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.BIRCH_SAPLING)
                .result(new ItemStack(Material.BIRCH_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapjungleoak")
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.OAK_SAPLING)
                .result(new ItemStack(Material.OAK_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapjungleacacia")
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.ACACIA_SAPLING)
                .result(new ItemStack(Material.ACACIA_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapjungledarkoak")
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.DARK_OAK_SAPLING)
                .result(new ItemStack(Material.DARK_OAK_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapjunglespruce")
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.SPRUCE_SAPLING)
                .result(new ItemStack(Material.SPRUCE_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapjunglemangrove")
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.JUNGLE_LOG)
                .ingredient(Material.MANGROVE_PROPAGULE)
                .result(new ItemStack(Material.MANGROVE_LOG, 8))
                .build());
        if (Materials.CHERRY_LOG != null && Materials.CHERRY_SAPLING != null) {
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swapjunglecherry")
                    .ingredient(Material.JUNGLE_LOG)
                    .ingredient(Material.JUNGLE_LOG)
                    .ingredient(Material.JUNGLE_LOG)
                    .ingredient(Material.JUNGLE_LOG)
                    .ingredient(Material.JUNGLE_LOG)
                    .ingredient(Material.JUNGLE_LOG)
                    .ingredient(Material.JUNGLE_LOG)
                    .ingredient(Material.JUNGLE_LOG)
                    .ingredient(Materials.CHERRY_SAPLING)
                    .result(new ItemStack(Materials.CHERRY_LOG, 8))
                    .build());
        }
        if (Materials.PALE_OAK_LOG != null && Materials.PALE_OAK_SAPLING != null) {
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swapjunglepaleoak")
                    .ingredient(Material.JUNGLE_LOG)
                    .ingredient(Material.JUNGLE_LOG)
                    .ingredient(Material.JUNGLE_LOG)
                    .ingredient(Material.JUNGLE_LOG)
                    .ingredient(Material.JUNGLE_LOG)
                    .ingredient(Material.JUNGLE_LOG)
                    .ingredient(Material.JUNGLE_LOG)
                    .ingredient(Material.JUNGLE_LOG)
                    .ingredient(Materials.PALE_OAK_SAPLING)
                    .result(new ItemStack(Materials.PALE_OAK_LOG, 8))
                    .build());
        }

        //Spruce -> Types
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapsprucebirch")
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.BIRCH_SAPLING)
                .result(new ItemStack(Material.BIRCH_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapspruceoak")
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.OAK_SAPLING)
                .result(new ItemStack(Material.OAK_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapspruceacacia")
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.ACACIA_SAPLING)
                .result(new ItemStack(Material.ACACIA_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapsprucedarkoak")
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.DARK_OAK_SAPLING)
                .result(new ItemStack(Material.DARK_OAK_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapsprucejungle")
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.JUNGLE_SAPLING)
                .result(new ItemStack(Material.JUNGLE_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapsprucemangrove")
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.SPRUCE_LOG)
                .ingredient(Material.MANGROVE_PROPAGULE)
                .result(new ItemStack(Material.MANGROVE_LOG, 8))
                .build());
        if (Materials.CHERRY_LOG != null && Materials.CHERRY_SAPLING != null) {
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swapsprucecherry")
                    .ingredient(Material.SPRUCE_LOG)
                    .ingredient(Material.SPRUCE_LOG)
                    .ingredient(Material.SPRUCE_LOG)
                    .ingredient(Material.SPRUCE_LOG)
                    .ingredient(Material.SPRUCE_LOG)
                    .ingredient(Material.SPRUCE_LOG)
                    .ingredient(Material.SPRUCE_LOG)
                    .ingredient(Material.SPRUCE_LOG)
                    .ingredient(Materials.CHERRY_SAPLING)
                    .result(new ItemStack(Materials.CHERRY_LOG, 8))
                    .build());
        }
        if (Materials.PALE_OAK_LOG != null && Materials.PALE_OAK_SAPLING != null) {
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swapsprucepaleoak")
                    .ingredient(Material.SPRUCE_LOG)
                    .ingredient(Material.SPRUCE_LOG)
                    .ingredient(Material.SPRUCE_LOG)
                    .ingredient(Material.SPRUCE_LOG)
                    .ingredient(Material.SPRUCE_LOG)
                    .ingredient(Material.SPRUCE_LOG)
                    .ingredient(Material.SPRUCE_LOG)
                    .ingredient(Material.SPRUCE_LOG)
                    .ingredient(Materials.PALE_OAK_SAPLING)
                    .result(new ItemStack(Materials.PALE_OAK_LOG, 8))
                    .build());
        }

        //Mangrove -> Types
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapmangrovebirch")
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.BIRCH_SAPLING)
                .result(new ItemStack(Material.BIRCH_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapmangroveoak")
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.OAK_SAPLING)
                .result(new ItemStack(Material.OAK_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapmangroveacacia")
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.ACACIA_SAPLING)
                .result(new ItemStack(Material.ACACIA_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapmangrovedarkoak")
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.DARK_OAK_SAPLING)
                .result(new ItemStack(Material.DARK_OAK_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapmangrovejungle")
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.JUNGLE_SAPLING)
                .result(new ItemStack(Material.JUNGLE_LOG, 8))
                .build());
        registerRecipe(AdaptRecipe.shapeless()
                .key("axe-swapmangrovespruce")
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.MANGROVE_LOG)
                .ingredient(Material.SPRUCE_SAPLING)
                .result(new ItemStack(Material.SPRUCE_LOG, 8))
                .build());
        if (Materials.CHERRY_LOG != null && Materials.CHERRY_SAPLING != null) {
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swapmangrovecherry")
                    .ingredient(Material.MANGROVE_LOG)
                    .ingredient(Material.MANGROVE_LOG)
                    .ingredient(Material.MANGROVE_LOG)
                    .ingredient(Material.MANGROVE_LOG)
                    .ingredient(Material.MANGROVE_LOG)
                    .ingredient(Material.MANGROVE_LOG)
                    .ingredient(Material.MANGROVE_LOG)
                    .ingredient(Material.MANGROVE_LOG)
                    .ingredient(Materials.CHERRY_SAPLING)
                    .result(new ItemStack(Materials.CHERRY_LOG, 8))
                    .build());
        }
        if (Materials.PALE_OAK_LOG != null && Materials.PALE_OAK_SAPLING != null) {
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swapmangrovepaleoak")
                    .ingredient(Material.MANGROVE_LOG)
                    .ingredient(Material.MANGROVE_LOG)
                    .ingredient(Material.MANGROVE_LOG)
                    .ingredient(Material.MANGROVE_LOG)
                    .ingredient(Material.MANGROVE_LOG)
                    .ingredient(Material.MANGROVE_LOG)
                    .ingredient(Material.MANGROVE_LOG)
                    .ingredient(Material.MANGROVE_LOG)
                    .ingredient(Materials.PALE_OAK_SAPLING)
                    .result(new ItemStack(Materials.PALE_OAK_LOG, 8))
                    .build());
        }

        //Cherry -> Types
        if (Materials.CHERRY_LOG != null && Materials.CHERRY_SAPLING != null) {
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swapcherrybirch")
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Material.BIRCH_SAPLING)
                    .result(new ItemStack(Material.BIRCH_LOG, 8))
                    .build());
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swapcherryoak")
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Material.OAK_SAPLING)
                    .result(new ItemStack(Material.OAK_LOG, 8))
                    .build());
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swapcherryacacia")
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Material.ACACIA_SAPLING)
                    .result(new ItemStack(Material.ACACIA_LOG, 8))
                    .build());
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swapcherrydarkoak")
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Material.DARK_OAK_SAPLING)
                    .result(new ItemStack(Material.DARK_OAK_LOG, 8))
                    .build());
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swapcherryjungle")
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Material.JUNGLE_SAPLING)
                    .result(new ItemStack(Material.JUNGLE_LOG, 8))
                    .build());
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swapcherryspruce")
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Materials.CHERRY_LOG)
                    .ingredient(Material.SPRUCE_SAPLING)
                    .result(new ItemStack(Material.SPRUCE_LOG, 8))
                    .build());
            if (Materials.PALE_OAK_LOG != null && Materials.PALE_OAK_SAPLING != null) {
                registerRecipe(AdaptRecipe.shapeless()
                        .key("axe-swapcherrypaleoak")
                        .ingredient(Materials.CHERRY_LOG)
                        .ingredient(Materials.CHERRY_LOG)
                        .ingredient(Materials.CHERRY_LOG)
                        .ingredient(Materials.CHERRY_LOG)
                        .ingredient(Materials.CHERRY_LOG)
                        .ingredient(Materials.CHERRY_LOG)
                        .ingredient(Materials.CHERRY_LOG)
                        .ingredient(Materials.CHERRY_LOG)
                        .ingredient(Materials.PALE_OAK_SAPLING)
                        .result(new ItemStack(Materials.PALE_OAK_LOG, 8))
                        .build());
            }
        }

        //Pale Oak -> Types
        if (Materials.PALE_OAK_LOG != null && Materials.PALE_OAK_SAPLING != null) {
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swappaleoakbirch")
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Material.BIRCH_SAPLING)
                    .result(new ItemStack(Material.BIRCH_LOG, 8))
                    .build());
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swappaleoakoak")
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Material.OAK_SAPLING)
                    .result(new ItemStack(Material.OAK_LOG, 8))
                    .build());
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swappaleoakacacia")
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Material.ACACIA_SAPLING)
                    .result(new ItemStack(Material.ACACIA_LOG, 8))
                    .build());
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swappaleoakdarkoak")
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Material.DARK_OAK_SAPLING)
                    .result(new ItemStack(Material.DARK_OAK_LOG, 8))
                    .build());
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swappaleoakjungle")
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Material.JUNGLE_SAPLING)
                    .result(new ItemStack(Material.JUNGLE_LOG, 8))
                    .build());
            registerRecipe(AdaptRecipe.shapeless()
                    .key("axe-swappaleoakspruce")
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Materials.PALE_OAK_LOG)
                    .ingredient(Material.SPRUCE_SAPLING)
                    .result(new ItemStack(Material.SPRUCE_LOG, 8))
                    .build());
            if (Materials.CHERRY_LOG != null && Materials.CHERRY_SAPLING != null) {
                registerRecipe(AdaptRecipe.shapeless()
                        .key("axe-swappaleoakcherry")
                        .ingredient(Materials.PALE_OAK_LOG)
                        .ingredient(Materials.PALE_OAK_LOG)
                        .ingredient(Materials.PALE_OAK_LOG)
                        .ingredient(Materials.PALE_OAK_LOG)
                        .ingredient(Materials.PALE_OAK_LOG)
                        .ingredient(Materials.PALE_OAK_LOG)
                        .ingredient(Materials.PALE_OAK_LOG)
                        .ingredient(Materials.PALE_OAK_LOG)
                        .ingredient(Materials.CHERRY_SAPLING)
                        .result(new ItemStack(Materials.CHERRY_LOG, 8))
                        .build());
            }
        }
    }

    @Override
    public void addStats(int level, Element v) {
        v.addLore(C.GREEN + "+ " + C.GRAY + Localizer.dLocalize("axe.log_swap.lore1"));
    }


    @Override
    public void onTick() {
    }

    @Override
    public boolean isEnabled() {
        return getConfig().enabled;
    }

    @Override
    public boolean isPermanent() {
        return getConfig().permanent;
    }

    @NoArgsConstructor
    protected static class Config {
        @com.volmit.adapt.util.config.ConfigDoc(value = "Keeps this adaptation permanently active once learned.", impact = "True removes the normal learn/unlearn flow and treats it as always learned.")
        boolean permanent = true;
        @com.volmit.adapt.util.config.ConfigDoc(value = "Enables or disables this feature.", impact = "Set to false to disable behavior without uninstalling files.")
        boolean enabled = true;
        @com.volmit.adapt.util.config.ConfigDoc(value = "Base knowledge cost used when learning this adaptation.", impact = "Higher values make each level cost more knowledge.")
        int baseCost = 2;
        @com.volmit.adapt.util.config.ConfigDoc(value = "Maximum level a player can reach for this adaptation.", impact = "Higher values allow more levels; lower values cap progression sooner.")
        int maxLevel = 1;
        @com.volmit.adapt.util.config.ConfigDoc(value = "Knowledge cost required to purchase level 1.", impact = "Higher values make unlocking the first level more expensive.")
        int initialCost = 2;
        @com.volmit.adapt.util.config.ConfigDoc(value = "Scaling factor applied to higher adaptation levels.", impact = "Higher values increase level-to-level cost growth.")
        double costFactor = 1;
    }
}