
plugins {
    id 'java'
}

dependencies {
    compileOnly(libs.velocity)
    annotationProcessor(libs.velocity)

    compileOnly('de.crazydev22.slimjar.helper:velocity:2.1.9')
    compileOnly(libs.lettuce)
    compileOnly(libs.toml4j)
    compileOnly(libs.fastutil)
}

def templateSource = file('src/main/templates')
def templateDest = layout.buildDirectory.dir('generated/sources/templates')
def generateTemplates = tasks.register('generateTemplates', Copy) {
    inputs.properties([
        id     : rootProject.name.toLowerCase(),
        name   : rootProject.name,
        version: rootProject.version,
    ])

    from(templateSource)
    into(templateDest)
    rename { String fileName -> "art/arcane/adapt/${fileName}" }
    expand(inputs.properties)
}

sourceSets {
    main {
        java {
            srcDir(generateTemplates.map { it.outputs })
        }
    }
}
